{\rtf1\ansi\ansicpg1252\cocoartf2821
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red209\green209\blue209;\red255\green255\blue255;}
{\*\expandedcolortbl;;\cssrgb\c85490\c85490\c85490;\cssrgb\c100000\c100000\c100000\c3922;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24\fsmilli12250 \cf2 \cb3 \expnd0\expndtw0\kerning0
[build]\
  command = "echo 'Hello World'"\
  publish = "."}